# Generated by Django 5.2.6 on 2025-09-23 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_chat', '0001_initial'),
    ]

    operations = [
    ]
