# Generated by Django 5.2.6 on 2025-09-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysettings',
            options={'verbose_name': 'Company Settings', 'verbose_name_plural': 'Company Settings'},
        ),
        migrations.AddField(
            model_name='companysettings',
            name='organization_address',
            field=models.TextField(blank=True, help_text='Organization address', null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='organization_logo',
            field=models.ImageField(blank=True, help_text='Organization logo for reports', null=True, upload_to='organization/'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='organization_name',
            field=models.CharField(default='Your Organization Name', help_text='Name of your organization/company', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='organization_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='organization_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
