# Generated by Django 5.2.6 on 2025-09-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_preferred_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('accountant', 'Accountant'), ('hr', 'HR'), ('viewer', 'Viewer')], max_length=50),
        ),
    ]
