# Generated by Django 5.2.6 on 2025-09-30 00:57

import django.utils.timezone
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(help_text='The name of the client organization', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the organization', null=True)),
                ('email', models.EmailField(help_text='Primary contact email', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('subscription_status', models.CharField(choices=[('trial', 'Free Trial'), ('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter Plan'), ('professional', 'Professional Plan'), ('enterprise', 'Enterprise Plan'), ('custom', 'Custom Plan')], default='starter', max_length=20)),
                ('paid_until', models.DateField(help_text='The date their subscription is valid until')),
                ('on_trial', models.BooleanField(default=True, help_text='If the organization is on trial')),
                ('trial_ends', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('ZAR', 'South African Rand (R)'), ('MXN', 'Mexican Peso ($)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Złoty (zł)'), ('RUB', 'Russian Ruble (₽)')], default='USD', help_text='Preferred currency for billing and invoices', max_length=3)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_users', models.PositiveIntegerField(default=5)),
                ('max_invoices_per_month', models.PositiveIntegerField(default=100)),
                ('max_storage_gb', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='client_logos/')),
                ('primary_color', models.CharField(default='#007bff', help_text='Brand primary color (hex)', max_length=7)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the client', null=True)),
            ],
            options={
                'verbose_name': 'Client Organization',
                'verbose_name_plural': 'Client Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('billing', 'Billing Contact'), ('technical', 'Technical Contact'), ('primary', 'Primary Contact'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClientUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('users', 'Active Users'), ('invoices', 'Invoices Created'), ('storage', 'Storage Used (MB)'), ('api_calls', 'API Calls'), ('login', 'User Login')], max_length=20)),
                ('value', models.PositiveIntegerField()),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_recorded', 'metric_type'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ssl_enabled', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
