# Generated by Django 5.2.6 on 2025-09-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options_alter_domain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('CAD', 'Canadian Dollar (C$)'), ('AUD', 'Australian Dollar (A$)'), ('JPY', 'Japanese Yen (¥)'), ('CHF', 'Swiss Franc (CHF)'), ('CNY', 'Chinese Yuan (¥)'), ('INR', 'Indian Rupee (₹)'), ('BRL', 'Brazilian Real (R$)'), ('ZAR', 'South African Rand (R)'), ('MXN', 'Mexican Peso ($)'), ('SGD', 'Singapore Dollar (S$)'), ('HKD', 'Hong Kong Dollar (HK$)'), ('NZD', 'New Zealand Dollar (NZ$)'), ('SEK', 'Swedish Krona (kr)'), ('NOK', 'Norwegian Krone (kr)'), ('DKK', 'Danish Krone (kr)'), ('PLN', 'Polish Złoty (zł)'), ('RUB', 'Russian Ruble (₽)')], default='USD', help_text='Preferred currency for billing and invoices', max_length=3),
        ),
    ]
