# Generated by Django 5.2.6 on 2025-09-23 09:52

import accounts.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_journalentry_journalentryline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Descriptive title for the document', max_length=200)),
                ('document_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('bank_statement', 'Bank Statement'), ('contract', 'Contract'), ('check', 'Check'), ('voucher', 'Voucher'), ('other', 'Other')], default='other', help_text='Type of source document', max_length=20)),
                ('file', models.FileField(help_text='Upload the source document file', upload_to=accounts.models.source_document_upload_path)),
                ('description', models.TextField(blank=True, help_text='Optional description or notes about the document', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('content_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry this document is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='accounts.journalentry')),
                ('transaction', models.ForeignKey(blank=True, help_text='Legacy transaction this document is attached to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='accounts.transaction')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Source Document',
                'verbose_name_plural': 'Source Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
