# Generated by Django 5.2.6 on 2025-09-23 19:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sourcedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Opening balance for this account', max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='opening_balance_date',
            field=models.DateField(blank=True, help_text='Date of the opening balance', null=True),
        ),
    ]
