# Generated by Django 5.2.6 on 2025-09-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='Your Organization Name', help_text='Name of your organization/company', max_length=200)),
                ('organization_address', models.TextField(blank=True, help_text='Organization address', null=True)),
                ('organization_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('organization_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_website', models.URLField(blank=True, null=True)),
                ('organization_logo', models.ImageField(blank=True, help_text='Organization logo for reports', null=True, upload_to='organization/')),
                ('fiscal_year_start', models.DateField()),
                ('currency', models.CharField(max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
