# Generated by Django 5.2.6 on 2025-09-22 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_accounts', models.BooleanField(default=True, help_text='Audit Account model changes')),
                ('audit_journal_entries', models.BooleanField(default=True, help_text='Audit Journal Entry changes')),
                ('audit_transactions', models.BooleanField(default=True, help_text='Audit Transaction changes')),
                ('audit_users', models.BooleanField(default=True, help_text='Audit User changes')),
                ('audit_clients', models.BooleanField(default=False, help_text='Audit Client changes')),
                ('audit_invoices', models.BooleanField(default=False, help_text='Audit Invoice changes')),
                ('retention_days', models.PositiveIntegerField(default=365, help_text='Number of days to keep audit logs (0 = forever)')),
                ('audit_create', models.BooleanField(default=True, help_text='Audit create actions')),
                ('audit_update', models.BooleanField(default=True, help_text='Audit update actions')),
                ('audit_delete', models.BooleanField(default=True, help_text='Audit delete actions')),
                ('audit_view', models.BooleanField(default=False, help_text='Audit view actions (creates many logs)')),
                ('audit_login', models.BooleanField(default=True, help_text='Audit login/logout actions')),
                ('email_on_critical_changes', models.BooleanField(default=False, help_text='Send email notifications for critical changes')),
                ('notification_email', models.EmailField(blank=True, help_text='Email address for audit notifications', max_length=254)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Audit Settings',
                'verbose_name_plural': 'Audit Settings',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-login_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('post_journal', 'Post Journal Entry'), ('unpost_journal', 'Unpost Journal Entry')], max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('session_key', models.CharField(blank=True, max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx')],
            },
        ),
    ]
